# Generated by Django 6.0.3 on 2026-03-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='One ingredient per line')),
                ('method', models.TextField(help_text='One step per line')),
                ('prep_time_min', models.IntegerField(default=10)),
                ('cook_time_min', models.IntegerField(default=20)),
                ('servings', models.IntegerField(default=2)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('drink', 'Drink'), ('dessert', 'Dessert')], max_length=20)),
                ('diet_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('eggetarian', 'Eggetarian')], max_length=20)),
                ('season', models.CharField(choices=[('all', 'All'), ('summer', 'Summer'), ('winter', 'Winter'), ('monsoon', 'Monsoon'), ('spring', 'Spring')], default='all', max_length=20)),
                ('health_tags', models.CharField(choices=[('all', 'All'), ('diabetes', 'Diabetes Friendly'), ('hypertension', 'BP Friendly'), ('thyroid', 'Thyroid Friendly'), ('pcod', 'PCOD/PCOS Friendly'), ('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('heart', 'Heart Healthy'), ('cholesterol', 'Low Cholesterol'), ('anemia', 'Anemia Friendly'), ('gym', 'Gym / High Protein'), ('general', 'General Healthy')], max_length=50)),
                ('suitable_for', models.TextField(blank=True)),
                ('avoid_for', models.TextField(blank=True)),
                ('calories', models.IntegerField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('sugar_g', models.FloatField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
