# Generated by Django 6.0.3 on 2026-03-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='season',
            field=models.CharField(choices=[('all', 'All Seasons'), ('summer', 'Summer'), ('winter', 'Winter'), ('monsoon', 'Monsoon'), ('spring', 'Spring')], default='all', max_length=20),
        ),
    ]
